int LocationName;
int act4 = 0;
int location;
int LoadLocation = 0;

int BotGetLocation();
int DetectHiddenCamp(BITMAPCAPTURE *grab);
int DetectCaldey(BITMAPCAPTURE *grab);
int DetectCity(BITMAPCAPTURE *grab);
int GetLocationHash(BITMAPCAPTURE *grab);
int DetectNewTristram(BITMAPCAPTURE *grab);
int DetectLocation(BITMAPCAPTURE *grab);
int DetectBastion(BITMAPCAPTURE *grab);

int LOCATION_KAMENNIY_FORT = 244116;
int LOCATION_NEDRA_GORI_ARREAT = 345582;
int LOCATION_MOST_RAKKISA = 113866;
int LOCATION_NIZHNIE_ETASHI_KREPOSTI_1 = 560054;
int LOCATION_NIZHNIE_ETASHI_KREPOSTI_3 = 578854;
int LOCATION_NIZHNIE_ETASHI_KREPOSTI_2 = 592794;
int LOCATION_ARREATSKIY_KRATER_1 = 481624;
int LOCATION_BASHNYA_OBRECHENNUH_1 = 626838;
int LOCATION_ARREATSKIY_KRATER_2 = 514568;
int LOCATION_BASHNYA_PROKLYATIH_1 = 496666;
int LOCATION_MOST_KORSIKKA = 145362;
int LOCATION_POLYA_KROVAVOI_BOINY = 377546;
int LOCATION_POLE_BOYA = 236608;
int LOCATION_BASHNYA_OBRECHENNUH_2 = 659438;
int LOCATION_SERDCE_OBRECHENNUH = 555376;
int LOCATION_BASHNYA_PROKLYATIH_2 = 529570;
int LOCATION_SERDCE_PROKLYATIH_2 = 414236;
int LOCATION_SERDCE_GREHA = 397852;

extern BITMAPCAPTURE globalscreengrab;
extern BOOL CaptureScreen(BITMAPCAPTURE *bmpCapture);
extern int x,y;